from fila import Fila

fila = Fila(6)
print(fila.vazia())
print(fila.cheia())
fila.queue(3)
fila.queue(4)
fila.queue(5)
fila.queue(6)
fila.queue(7)
fila.queue(8)
fila.queue(9)
fila.imprimir()
print("---------------")
fila.dequeue()
fila.imprimir()
fila.queue(9)
print("---------------")
fila.imprimir()